### ISSUE TITLE
No clipboard 

### ISSUE THREAD

**Issue by FatalCreations** [t0thkr1s/revshellgen#14]
I'm trying to use this from termux which can't effect the clipboard unless it uses termux-api which pyperclip doesn't detect so it errors out, would it be possible for --no-copy or something to be added for such cases and for cases where one just doesn't want to give the script clipboard access

**Comment by p-i-c-o** [comment]
had this issue too, made my own fork that adds this feature alone, but don't use it on other operating systems:
[my fork](https://github.com/p-i-c-o/reverse-shell-termux)

**Comment by FatalCreations** [comment]
Nice 👍
