### ISSUE TITLE
Can't select IP.

### ISSUE THREAD

**Issue by Minisaints** [t0thkr1s/revshellgen#5]
Hello,

Nothing I know of has changed on my box but I can no longer select an IP. I can select up and down but cannot press enter to select? Bit odd.

Any help would be good.

Thanks.

![image](https://user-images.githubusercontent.com/34611622/109443636-f1495300-7a32-11eb-82c4-2281f2ff61b5.png)

**Comment by mahatah** [comment]
I confirm that I have the same issue.

**Comment by mahatah** [comment]
**update**
I have a workaround solution that is working for me. You might consider making the changes I made to line 81 of revshellgen.py.

Change:
     `elif keypress == readchar.key.ENTER:`
To:
     `elif keypress == '\n':`

**Comment by Minisaints** [comment]
> **update**
> I have a workaround solution that is working for me. You might consider making the changes I made to line 81 of revshellgen.py.
> 
> Change:
> `elif keypress == readchar.key.ENTER:`
> To:
> `elif keypress == '\n':`

Ah thanks for that. I'll try it when I get back.

**Comment by Billygladue** [comment]
need help access IP address and get help to set up secure site

**Comment by Minisaints** [comment]
> > **update**
> > I have a workaround solution that is working for me. You might consider making the changes I made to line 81 of revshellgen.py.
> > Change:
> > `elif keypress == readchar.key.ENTER:`
> > To:
> > `elif keypress == '\n':`
> 
> Ah thanks for that. I'll try it when I get back.

This solution works great thanks. :)

**Comment by t0thkr1s** [comment]
Hi! 

I'm a bit late but I'd love to fix this issue! @mahatah Glad you figured out the problem. Can you make a pull request regarding this change that I can review / test?
